# Generated by Django 5.2.8 on 2025-12-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("exchange", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "previous_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "day_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "day_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stocks",
                "ordering": ["ticker"],
                "indexes": [
                    models.Index(fields=["ticker"], name="stocks_ticker_aa19f8_idx"),
                    models.Index(fields=["sector"], name="stocks_sector_88fdef_idx"),
                    models.Index(
                        fields=["last_updated"], name="stocks_last_up_0781d1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("open", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "adjusted_close",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("volume", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "stock_prices",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-date"], name="stock_price_stock_i_458ba8_idx"
                    ),
                    models.Index(fields=["date"], name="stock_price_date_9d4b65_idx"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="TechnicalIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("SMA", "Simple Moving Average"),
                            ("EMA", "Exponential Moving Average"),
                            ("RSI", "Relative Strength Index"),
                            ("MACD", "Moving Average Convergence Divergence"),
                            ("BB", "Bollinger Bands"),
                            ("STOCH", "Stochastic Oscillator"),
                            ("ADX", "Average Directional Index"),
                            ("ATR", "Average True Range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("value", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "value2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "value3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("period", models.IntegerField(default=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "technical_indicators",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "indicator_type", "-date"],
                        name="technical_i_stock_i_95701d_idx",
                    ),
                    models.Index(
                        fields=["indicator_type", "date"],
                        name="technical_i_indicat_0527e2_idx",
                    ),
                ],
                "unique_together": {("stock", "indicator_type", "date", "period")},
            },
        ),
    ]
